from django.db import models

class TaxDataModel(models.Model):
    user_id = models.CharField(max_length=200)
    company_id = models.CharField(max_length=200)
    company_name = models.CharField(max_length=200)
    npwp = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    region = models.CharField(max_length=200)
    post_code = models.IntegerField()
    invoice_id = models.CharField(max_length=200)
    vendor_id = models.CharField(max_length=200)
    vendor_name = models.CharField(max_length=200)
    commercial_invoice_number = models.CharField(max_length=200)
    transaction_type = models.CharField(max_length=200)
    status_start = models.CharField(max_length=200)
    status_tax_summary = models.CharField(max_length=200)
    invoice_date = models.DateField()
    due_date = models.CharField(max_length=200)
    item_name = models.CharField(max_length=200)
    unitprice = models.IntegerField()
    quantity = models.IntegerField()
    discount = models.IntegerField()
    gross_amount = models.IntegerField()
    tax_amount = models.IntegerField()
    total_amount = models.IntegerField()
    tax_period = models.CharField(max_length=200)
    revision = models.IntegerField()
    reported_date = models.DateField()
    reported_status = models.CharField(max_length=200)
    reported_status_desc = models.CharField(max_length=200)
    tax_type = models.CharField(max_length=200)
    tax_document_number = models.CharField(max_length=200)
    tax_document_date = models.DateField()
    approved_date = models.DateField()
